apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: iris-api
spec:
  selector:
    matchLabels:
      app: iris-api
    
  endpoints:
    - port: http
      path: /metrics
      interval: 30s