apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iris-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/iam-dushyant/ml-k8s-docker-experiment.git
    targetRevision: feature/v2
    path: k8s
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true