name: CI

on:
  push:
    branches: 
      - main      
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  test-build-scan:
    runs-on: ubuntu-latest

    env:
      MODEL_VERSION: v2
      PYTHONPATH: .

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train versioned model
      run: |
        python src/train.py
        test -f model/v2/iris_rf.joblib
        test -f model/v2/metadata.json

    - name: Run tests
      run: |
        python -m pytest -q

    - name: Build Docker image
      run: |
        docker build -t iris-api:${{ github.sha }} .
    
    - name: Scan Trivy for vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: iris-api:${{ github.sha }}
        format: table
        exit-code: "1"
        ignore-unfixed: true
